# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-10 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('rus_name', models.CharField(db_index=True, max_length=200, verbose_name='Название на русском')),
                ('nalog_system', models.CharField(blank=True, choices=[('usn', 'usn'), ('nds', 'nds')], db_index=True, max_length=3, verbose_name='Система налогооблажения')),
                ('unp', models.PositiveIntegerField(default=1, verbose_name='УНП')),
                ('bank_schet', models.CharField(db_index=True, max_length=100, verbose_name='Банковский счет')),
                ('bank_BIK', models.CharField(db_index=True, max_length=100, verbose_name='IBAN')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Е-mail')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
