# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bank_BIK',
        ),
        migrations.RemoveField(
            model_name='client',
            name='bank_schet',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='rus_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='unp',
        ),
    ]
