# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180613_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rus_name',
            field=models.CharField(db_index=True, default=1, max_length=200, verbose_name='Название на русском'),
            preserve_default=False,
        ),
    ]
