# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-18 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client_rus_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='rus_name',
        ),
        migrations.AddField(
            model_name='client',
            name='bank_BIK',
            field=models.CharField(db_index=True, default=1, max_length=100, verbose_name='IBAN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='bank_schet',
            field=models.CharField(db_index=True, default=1, max_length=100, verbose_name='Банковский счет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Е-mail'),
        ),
        migrations.AddField(
            model_name='client',
            name='unp',
            field=models.PositiveIntegerField(default=1, verbose_name='УНП'),
        ),
    ]
