# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-04 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180618_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bank_BIK',
        ),
        migrations.RemoveField(
            model_name='client',
            name='bank_schet',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nalog_system',
        ),
        migrations.RemoveField(
            model_name='client',
            name='unp',
        ),
        migrations.AddField(
            model_name='client',
            name='rus_name',
            field=models.CharField(db_index=True, default=1, max_length=200, verbose_name='Название на русском'),
            preserve_default=False,
        ),
    ]
