# Generated by Django 2.1.4 on 2019-01-22 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taverns', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='work_place',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='taverns.Taverna'),
        ),
    ]
