# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-23 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение товара')),
                ('price', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Цена')),
                ('weight', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Вес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Taverna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to='place_icons/', verbose_name='Аватарка заведения')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('adres', models.CharField(db_index=True, max_length=200, verbose_name='Адрес')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('work_time', models.CharField(db_index=True, max_length=200, verbose_name='Время работы')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='clients.Client', verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='taverns.Taverna', verbose_name='Заведение'),
        ),
        migrations.AlterIndexTogether(
            name='taverna',
            index_together=set([('id', 'name', 'slug')]),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([('id', 'name', 'slug')]),
        ),
    ]
