# Generated by Django 2.1.4 on 2019-01-22 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, default='products/deafult.png', upload_to='products/', verbose_name='Изображение товара')),
                ('price', models.FloatField(blank=True, db_index=True, verbose_name='Цена')),
                ('weight', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Вес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Taverna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, default='place_icons/default.png', upload_to='place_icons/', verbose_name='Аватарка заведения')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('city', models.CharField(db_index=True, default='', max_length=200, verbose_name='Город')),
                ('street', models.CharField(db_index=True, default='', max_length=200, verbose_name='Улица')),
                ('building', models.CharField(db_index=True, default='', max_length=200, verbose_name='Дом')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('work_time', models.CharField(db_index=True, max_length=200, verbose_name='Время работы')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='clients.Owner', verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='taverns.Taverna', verbose_name='Заведение'),
        ),
        migrations.AlterIndexTogether(
            name='taverna',
            index_together={('id', 'name', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'name', 'slug')},
        ),
    ]
