# Generated by Django 2.0.7 on 2018-07-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение товара')),
                ('price', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Цена')),
                ('weight', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Вес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
                'verbose_name': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='Taverna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to='place_icons/', verbose_name='Авартка заведения')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('adres', models.CharField(db_index=True, max_length=200, verbose_name='Адрес')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('work_time', models.CharField(db_index=True, max_length=200, verbose_name='Время работы')),
            ],
            options={
                'verbose_name_plural': 'Заведения',
                'ordering': ['name'],
                'verbose_name': 'Заведение',
            },
        ),
        migrations.AlterIndexTogether(
            name='taverna',
            index_together={('id', 'name', 'slug')},
        ),
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='taverns.Taverna', verbose_name='Заведение'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'name', 'slug')},
        ),
    ]
