# Generated by Django 2.1.4 on 2019-01-22 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taverns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointed_time', models.TimeField(default=datetime.time(16, 0))),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('item_status', models.CharField(choices=[('wait', 'Ожидает'), ('ready', 'Готов'), ('paid', 'Оплачен')], db_index=True, default=('wait', 'Ожидает'), max_length=20, verbose_name='статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('sess_id', models.CharField(db_index=True, max_length=320, verbose_name='Сессия')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='taverns.Product')),
            ],
        ),
    ]
