# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-13 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(blank=True, choices=[('ожидает', 'wait'), ('готов', 'ready'), ('оплачен', 'paid')], db_index=True, max_length=20, verbose_name='статус заказа'),
        ),
    ]
