# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-21 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180820_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(db_index=True, default=2, max_length=320, verbose_name='Сессия'),
            preserve_default=False,
        ),
    ]
