# Generated by Django 2.1 on 2018-09-27 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2018, 9, 27)),
        ),
    ]
